function normalization_t1(struct_dir, spm_path)
% Normalization function runs the normalization preprocessing step
% 
%   Input
%       struct_dir: Structural directory
%       spm_path: String specifying your SPM path
%
%   Output
%       None

warning off

% Select relevant volumes (c1, c2, c3, etc. files)
volumes = spm_select('fplist', struct_dir, '^c.*\.nii$');

% Manually select the deformation field generated by segmentation
def_field = spm_select('fplist', struct_dir, '^y_.*\.nii$');  % Deformation field

% Initialize the matlabbatch structure
matlabbatch{1}.spm.spatial.normalise.write.subj.def = {def_field};  % Deformation field
matlabbatch{1}.spm.spatial.normalise.write.subj.resample = cellstr(volumes);  % Resample the tissue masks

% Set bounding box and voxel size options
matlabbatch{1}.spm.spatial.normalise.write.woptions.bb = [-78 -112 -70; 78 76 85];
matlabbatch{1}.spm.spatial.normalise.write.woptions.vox = [1 1 1];
matlabbatch{1}.spm.spatial.normalise.write.woptions.interp = 4;

% Run job
spm_jobman('run', matlabbatch)
clear matlabbatch
end